name: CI

on:
  pull_request:
    paths:
      - '**.ts'
      - '**eslint**'
      - 'package-lock.json'
      - '.github/workflows/lint.yml'

jobs:
  lint:
    name: Lint
    env:
      CI: true
      HUSKY_SKIP_INSTALL: true
      FORCE_COLOR: 2

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v1

      - name: Install Packages
        run: npm ci

      - name: Lint
        run: |
          git branch -r
          git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/master
          git branch -a
          CHANGED_TS=$(git --no-pager diff --name-only ..origin/master | grep '/.*\.ts$' | xargs ls -d 2>/dev/null | paste -sd " " -)
          if [[ -z $(sed -e 's/[[:space:]]*$//' <<<${CHANGED_TS}) ]] || [[ "$CHANGED_TS" == "." ]];
            then
              npm run -s lint
            else
              node node_modules/eslint/bin/eslint $CHANGED_TS
          fi

      - name: Typecheck
        run: npx tsc --noEmit
